config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations/registrations'
  }

  root 'pages#home'
  get 'pages/home'
  get 'pages/extrainfo'

  resources :users
  resources :character_cards

  resources :messages
  delete '/comments/:id', to: 'messages#destroy'

 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def after_sign_in_path_for(resource)
    root_path
  end
end

app/models/character_card.rb
class CharacterCard < ApplicationRecord
  belongs_to :user

  mount_uploader :avatar, AvatarUploader

  validates :name, presence: true
  validates :name, length: {minimum: 3, too_short: "Name has to be at least %{count} characters long"}

  # callback to check if the card is protected or not
  before_destroy :check_if_protected

  # cannot be called outside of the model
  private

  def check_if_protected
    # checks whether the protected attribute of the current instance is true or not
    if self.protected?
      # iftrue, it adds an error message
      errors.add(:protected, "This card is protected and cannot be deleted.")
      # stops deleting the current instance and return the error message to the caller
      throw(:abort)
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages, dependent: :destroy
  has_many :character_cards, dependent: :destroy

  validates :email, presence: true, uniqueness: true

  # after_create :protected_character_cards

  # private

  # def protected_character_cards
  #     unless character_cards.exists?
  #       character_cards.create(name: "Hello Kitty",  birthday: "1 November", location: "London, England",   fav_food: "Apple pie",  fave_colour: "red",   image: "https://upload.wikimedia.org/wikipedia/en/0/05/Hello_kitty_character_portrait.png",   protected: true)
  #       character_cards.create(name: "My Melody",   birthday: "January 18", location: "Mary Land",   fav_food: "Almond pound cake",   fave_colour: "Pink",   image: "https://i.pinimg.com/564x/f0/73/93/f0739363ac24c6c52465ec602b0d65de.jpg",  protected: true)
  #       character_cards.create(name: "Gudetama",   birthday: "November 3",  location: "Japan",  fav_food: "Rice, bacon", fave_colour: "Yellow",  image: "https://i.pinimg.com/564x/47/63/8a/47638a7d1c2a2d505eed34a959d1e883.jpg",  protected: true)
  #       character_cards.create(name: "Little Twin Stars",  birthday: "December 24", location: "The Starry Sky",  fav_food: "Marshmallows", fave_colour: "Pink and blue", image: "https://i.pinimg.com/564x/75/38/64/7538641e44d0d7cae6f61dbc1463284c.jpg", protected: true)
  #       character_cards.create(name: "Cinnamoroll", birthday: "March 6", location: "Sky", fav_food: "Cinnamon rolls", fave_colour: "Light blue", image: "https://i.pinimg.com/564x/fa/b3/4f/fab34fd87f97b37606633dc8fe0bbceb.jpg", protected: true)
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/character_cards_controller.rb
class CharacterCardsController < ApplicationController
    before_action :authenticate_user!

    def index
        @character_cards = current_user.character_cards.all
    end

    def show
        @character_card = CharacterCard.find(params[:id])
    end
  
    def new
        @character_card = CharacterCard.new
    end
  
    def edit
        @character_card = CharacterCard.find(params[:id])
    end
  
    def create 
        @character_card = current_user.character_cards.build(character_card_params)
        if @character_card.save
          redirect_to character_cards_path, notice: 'Character card was successfully created.'
        else
          render :new
        end
    end
  
    def update
        @character_card = CharacterCard.find(params[:id])
        @character_card.update!(params.require(:character_card).permit(:name, :birthday, :location, :fav_food, :fave_colour))
        redirect_to character_cards_path, notice: 'Character card was successfully updated.'

    end

    def destroy
        @character_card = CharacterCard.find(params[:id])
        if @character_card.protected?
          flash[:error] = "This character card is protected and cannot be deleted."
        else
          @character_card.destroy
          flash[:success] = "Character card was successfully deleted."
        end
        redirect_to character_cards_path
    end

    private

    def character_card_params
        params.require(:character_card).permit(:name, :birthday, :location, :fav_food, :fave_colour)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_message, only: [:destroy]

    def index
      @message = Message.new
      @messages = Message.all.order(created_at: :desc)
    end
  
    def create
      @message = current_user.messages.build(message_params)
      @message.save
      redirect_to messages_path
    end
  
    def destroy
      @message.destroy
      redirect_to messages_path
    end
  
    private
  
    def set_message
      @message = current_user.messages.find(params[:id])
    end
  
    def message_params
      params.require(:message).permit(:message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:extrainfo]

  def home
  end

  def extrainfo
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, message: "Please sign in to view this page"
  before_action :set_user, only: [:show, :edit, :update, :destroy]

    def index
      @users = User.all
    end
  
    def show
      @user = User.find(params[:id])
    end
  
    def new
      @user = User.new
    end
  
    def edit
      @user = User.find(params[:id])
    end
  
    def create
      @user = User.new(user_params)
      redirect_to @user, notice: 'User was successfully created.'
    end
  
    def update
      @user = User.find(params[:id])
      if @user.update!(user_params)
        redirect_to users_path
      else
        render 'edit'
      end
    end
  
    def destroy
      @user.destroy
      redirect_to users_url, notice: 'User was successfully destroyed.'
    end
  
    private
    def set_user
        @user = User.find(params[:id])
    end

    # def user_params
    # params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :username, :bio, :profile_pic)
    # end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :bio)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/character_cards_helper.rb
module CharacterCardsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/character_cards/_card_template.html.erb
<div class="col-md-3 mb-4">
  <div class="card">
    <% if character_card.image.present? %>
        <%= image_tag(character_card.image, class: "card-img-top", size: "100x200")%>
    <% else %>
        <%= image_tag("default_prof_pic.png", class: "card-img-top", size: "100x200") %>
    <% end %> 
    <div class="card-body">
      <h5 class="card-title shrink-text"><%= character_card.name %></h5>
      <p class="card-text shrink-text">Birthday: <%= character_card.birthday %></p>
      <p class="card-text shrink-text">Location: <%= character_card.location %></p>
      <p class="card-text shrink-text">Favorite food: <%= character_card.fav_food %></p>
      <p class="card-text shrink-text">Favorite color: <%= character_card.fave_colour %></p>
      <%= link_to 'View', character_card_path(character_card), class: 'btnc btn-pink' %>
      <%= link_to 'Update', edit_character_card_path(character_card), class: 'btnc btn-pink' %>
      <%= link_to 'Delete', character_card_path(character_card), class: 'btnc btn-pink',  data: {turbo_method: :delete, turbo_confirm: "Are you sure want to delete #{character_card.name}?"}%>
    </div>
  </div>
</div>

app/views/character_cards/_form.html.erb
<%= form_for @character_card do |f|%>    

    <div class="col-md-4 mb-4 card-middle ">
        <div class="card longer m-2 card-middle">
            <% if @character_card.image.present? %>
                <%= image_tag(@character_card.image, class: "card-img-top", size: "100x200")%>
            <% else %>
                <%= image_tag("own_c.png", class: "card-img-top", size: "100x200") %>
            <% end %> 
                <div class="card-body">
                    <div class="card-body">
                        <div class="field">
                            <%= f.label :name, "Name" %>
                            <%= f.text_field :name %>
                        </div>
                        <div class="field">
                            <%= f.label :birthday, "Birthday" %>
                            <%= f.text_field :birthday %>
                        </div>
                        <div class="field">
                            <%= f.label :location, "Location" %>
                            <%= f.text_field :location %>
                        </div>
                        <div class="field">
                            <%= f.label :fav_food, "Favourite food" %>
                            <%= f.text_field :fav_food %>
                        </div>
                        <div class="field">
                            <%= f.label :fave_colour, "Favourite color" %>
                            <%= f.text_field :fave_colour %>
                        </div>
                <%= f.submit "Submit", :class => "btnc btn-pink m-2" %>
            </div>
        </div>
    </div>

<% end %>

app/views/character_cards/cards.html.erb
<h1 class="card-middle">
  <% if current_user %>
    <%= "#{current_user.username}'s favourite characters" %>
  <% else %>
    <%= "Favourite characters" %>
  <% end %>
</h1>

<div class="card-container">

    <% @character_cards.each do |character_card| %>
        <%= render partial: 'card_template', locals: { character_card: character_card } %>
    <% end %>
    
    <div class="col-md-3 mb-4">
    <div class="card">
        <%= image_tag("own_c.png", class: "card-img-top", size: "100x200") %>
        <div class="card-body">
        <h5 class="card-title shrink-text">Character's Name</h5>
        <p class="card-text shrink-text">Birthday: </p>
        <p class="card-text shrink-text">Location: </p>
        <p class="card-text shrink-text">Favorite food: </p>
        <p class="card-text shrink-text">Favorite color: </p>
        <%= link_to 'Add', new_character_card_path, type:"button" %>
        </div>
    </div>
    </div>
</div>

app/views/character_cards/edit.html.erb
<div class="card-middle">
    <h1> Edit <%= @character_card.name %> </h1>
    <div class="card-middle">
     <%= render 'form', class:"pad-top" %>
    </div>
</div>

app/views/character_cards/index.html.erb
<h1 class="card-middle">

    <div> Your character cards </div>

</h1>

<div class="card-container">

    <% @character_cards.each do |character_card| %>
        <%= render partial: 'card_template', locals: { character_card: character_card } %>
    <% end %>
    
    <div class="col-md-3 mb-4">
    <div class="card">
        <%= image_tag("own_c.png", class: "card-img-top", size: "100x200") %>
        <div class="card-body">
        <h5 class="card-title shrink-text">New Character</h5>
        <p class="card-text shrink-text">Birthday: </p>
        <p class="card-text shrink-text">Location: </p>
        <p class="card-text shrink-text">Favorite food: </p>
        <p class="card-text shrink-text">Favorite color: </p>
        <%= link_to 'Add', new_character_card_path, type:"button", class: 'btnc btn-pink'%>
        </div>
    </div>
    </div>
</div>

app/views/character_cards/new.html.erb
<div class="card-middle">
    <h3> Fill in the details for your new character </h3>

    <%= render 'form'%>

</div>

app/views/character_cards/show.html.erb
<div class="card-middle">
  <h1>Is <%= @character_card.name %> your favourite?</h1>

  <div class="col-md-4 mb-4 card-middle">
    <div class="card ">
      <% if @character_card.image.present? %>
          <%= image_tag(@character_card.image, class: "card-img-top", size: "100x200")%>
      <% else %>
          <%= image_tag("default_prof_pic.png", class: "card-img-top", size: "100x200") %>
      <% end %> 
      <div class="card-body">
        <h5 class="card-title"><%= @character_card.name %></h5>
        <p class="card-text">Birthday: <%= @character_card.birthday %></p>
        <p class="card-text">Location: <%= @character_card.location %></p>
        <p class="card-text">Favorite food: <%= @character_card.fav_food %></p>
        <p class="card-text">Favorite color: <%= @character_card.fave_colour %></p>
        <%= link_to "Back", character_cards_path, class: 'btnc btn-pink' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <title>SanrioFanClub</title>
  </head>


  <body>
    <header>
      <%= render 'pages/header' %>
    </header>

    <div class="container-fluid">
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissible fade show mt-3" role="alert">
           <%= content_tag :div, msg %>
            <button type="button" class="close " data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
         </div>
      <% end %>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
    

    <footer>

    </footer>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/messages/chat.html.erb
<h1>chat</h1>

app/views/messages/index.html.erb
<div class="card-middle">
    <h1>Comments</h1>

    <div class="card-middle">
        <h6>feel free to leave a forever comment</h6>
        <%= form_with model: Message.new do |form| %>
        <div class="align-row">
            <%= form.text_area :message, rows: 2, class: "form-control width" %>
            <%= form.submit "Submit", class: "btn-comment btn-pink" %>
        </div>
        <% end %>
    </div>

    <div class="card-middle ">
        <% @messages.each do |message| %>
            <div class="card-middle border">
                <h3 class="comment-name"><%= message.user.email.split('@').first %></h3>
                <div class="comment-field">
                    <%= message.message %>
                    <%# <% if current_user == message.user %>
                    <%# <%= link_to "Delete", messages_path(message), method: :delete, data: { confirm: "Are you sure you want to delete this message?" }, class: "btnc btn-pink" %> 
                    <%# <% end %> 
                </div>
            </div>
        <% end %>
    </div>

</div>

app/views/pages/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #fbe0e7;">
    <%= link_to "Sanri Fan Club", root_path, class: "navbar-brand", style: "color: #8f81bc;" %>  
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">

      <li class="nav-item">
        <%= link_to "Profile", users_path, class: "nav-link", style: "color: #8f81bc;" %>
      </li>

      <li class="nav-item">
        <%= link_to "Characters", character_cards_path, class: "nav-link", style: "color: #8f81bc;" %>
      </li>

      <li class="nav-item">
        <%= link_to "Comments", messages_path, class: "nav-link", style: "color: #8f81bc;" %>
      </li>

      <li class="nav-item">
        <%= link_to "Extra Info", pages_extrainfo_path, class: "nav-link", style: "color: #8f81bc;" %>
      </li>

    <% if user_signed_in? %>
        <li class="nav-item">
            <%# Welcome <%= current_user.email %>
            <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link", style: "color: #8f81bc;" %>    
        </li>
     <% else %>
        <li>
            <%= link_to "Login", new_user_session_path, class: "nav-link", style: "color: #8f81bc;" %>
        </li>
        <li>
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link", style: "color: #8f81bc;" %>
        </li>
    <% end %>

    </ul>
    <%# Bootstrap search bar - may wanna use it %>
    <%# <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-10" type="search" placeholder="Search" aria-label="Search" >
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="background-color: #ffff99; border-color: white; color: 944dff;">Search</button>
    </form> %>
          
  </div>
</nav>

app/views/pages/extrainfo.html.erb
<div class="card-middle full-page">
    <h1> Thank you for visiting my site! </h1>

    <p class="pad-top"> I created this website as my last 4th and final project for General Assembly Immersive course. </p>
    <p>It is not much but I m proud of it. Hope you enjoy your time here.</p>
</div>

app/views/pages/home.html.erb
<div class="card-middle full-page">
    <h1>Welcome to Sanrio Fan Club</h1>
    <p>all things cute and sweet</p>


    <% if user_signed_in? %>
    <p>I hope you have fun adding your own character cards and eventually be able to chat with others.</p>
    <% else %>
    <p>Please click <%= link_to "Login", new_user_session_path %> to sign in and start adding your characters.</p>
    <% end %>
</div>

app/views/users/edit.html.erb
<%= form_for @user do |f|%>    

    <div class="card-middle m-5">
        <h2> Edit your profile details </h2>
        <div class="card longer">
                    <div class="card-body larger-font card-middle space">
                        <div class="field card-middle m-larger">
                            <%= f.label :first_name, "First Name" %>
                            <%= f.text_field :first_name %>
                        </div>

                        <div class="field card-middle m-larger">
                            <%= f.label :last_name, "Last Name" %>
                            <%= f.text_field :last_name %>
                        </div>

                        <div class="field card-middle m-larger">
                            <%= f.label :username, "Username" %>
                            <%= f.text_field :username %>
                        </div>
                        
                        <div class="field card-middle m-larger">
                            <%= f.label :bio, "Bio" %>
                            <%= f.text_field :bio %>
                        </div>
                <%= f.submit "Submit", :class => "p-2 m-4 btn btn-outline-secondary btn-sm" %>
        </div>
    </div>

<% end %>

app/views/users/index.html.erb
<h1 class="card-middle"> Welcome <%= current_user.username %>! </h1>


<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-xl-10 col-md-12">
                <div class="card">
                    <div class="row m-l-0 m-r-0 mb-4 mt-4 mx-2">

                        <div class="col-sm-4 user-profile d-flex align-items-center justify-content-center">
                            <div class="card-block text-center">
                                <div class="align-items-center justify-content-center" style="height: 200px;">
                                    <% if current_user.profile_pic.present? %>
                                        <%= image_tag(current_user.profile_pic, size: "200x200")%>
                                    <% else %>
                                        <%= image_tag("default_prof_pic.png", size: "200x200")%>
                                    <% end %>                                
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-8">
                            <div class="card-block">
                                <h3 class="m-b-20 p-b-50 b-b-default f-w-600">Your Information</h3>

                                <div class="row">
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-400">First Name</p>
                                        <h6 class="text-muted f-w-400"> <%= current_user.first_name %> </h6>
                                    </div>
                                    <div class="col-sm-1">
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">Last Name</p>
                                        <h6 class="text-muted f-w-400"> <%= current_user.last_name %> </h6>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">Username</p>
                                        <h6 class="text-muted f-w-400"> <%= current_user.username %> </h6>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">Bio</p>
                                        <h6 class="text-muted f-w-400"> <%= current_user.bio %> </h6>
                                    </div>
                                </div>
                                        

                                <div class="row">
                                    <div class="col-sm-6">
                                        <%= link_to "Edit log in Details", edit_user_registration_path(@user), class:"btn btn-outline-secondary btn-sm" %>
                                    </div>
                                </div>
                                    
                                <div class="row">
                                    <div class="col-sm-6">
                                        <%= link_to "Edit Profile Details", edit_user_path(current_user), class: "mt-2 btn btn-outline-secondary btn-sm" %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>